#!/bin/sh
set -e
# reload system daemon to update configuration
systemctl daemon-reload
# ensure that pigpoi daemon
echo "INFO: enable pigpiod.service" >&2
systemctl enable pigpiod.service
systemctl start pigpiod.service
# enable fan control service
echo "INFO: enable geekworm-x735-fan.service" >&2
systemctl enable geekworm-x735-fan.service
systemctl start geekworm-x735-fan.service
# enable power monitoring service
echo "INFO: enable geekworm-x735-power.service" >&2
systemctl enable geekworm-x735-power.service
systemctl start geekworm-x735-power.service
# enable safe shutdown service
echo "INFO: enable geekworm-x735-safe-shutdown.service" >&2
systemctl enable geekworm-x735-safe-shutdown.service
systemctl start geekworm-x735-safe-shutdown.service
