#!/bin/sh
set -e

# disable fan control service
echo "INFO: disable geekworm-x735-fan.service" >&2
systemctl stop geekworm-x735-fan.service
systemctl disable geekworm-x735-fan.service
# disable power monitoring service
echo "INFO: disable geekworm-x735-power.service" >&2
systemctl stop geekworm-x735-power.service
systemctl disable geekworm-x735-power.service
# disable safe shutdown service
echo "INFO: disable geekworm-x735-safe-shutdown.service" >&2
systemctl disable geekworm-x735-safe-shutdown.service
